DROP TABLE IF EXISTS public.cities CASCADE;

CREATE TABLE public.cities (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NOT NULL,
	CONSTRAINT ck_cities_name CHECK ((length(name) <= 50)),
	CONSTRAINT pk_cities PRIMARY KEY (id),
	CONSTRAINT uq_cities UNIQUE (name)
);